APT_LIST=(bat
bleachbit
btop
build-essential
ca-certificates
curl
dialog
duf
efibootmgr
eza
fastfetch
fd-find
ffmpeg
flatpak
fonts-noto-core
fonts-noto-ui-core
gdu
gh
git
gnupg
htop
httpie
jq
language-pack-en
language-pack-gnome-en
nodejs
npm
pipx
plank
postgresql
postgresql-client
preload
python3-dev
python3-netifaces
python3-pip
python3-setuptools
redshift-gtk
ripgrep
sassc
sqlite3
sqlitebrowser
stacer
stow
systemd-zram-generator
television
thunderbird-locale-en
thunderbird-locale-en-us
tmux
trash-cli
tree
ulauncher
unp
unzip
vim
wget
xclip
xdg-desktop-portal
xdg-desktop-portal-gtk
xsel
zlib1g-dev
zoxide
zsh
)

BREW_LIST=(

fzf
gemini-cli
navi
node
thefuck
unzip
yazi
)

FLATPAK_LIST=(
com.discordapp.Discord
com.getpostman.Postman
com.github.IsmaelMartinez.teams_for_linux
com.github.tchx84.Flatseal
com.obsproject.Studio
io.dbeaver.DBeaverCommunity
it.mijorus.smile
md.obsidian.Obsidian
org.mozilla.Thunderbird
org.mozilla.firefox
org.telegram.desktop
)
