
$background = rgba(101418ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2d3135ff)

$inverse_primary = rgba(31628dff)

$inverse_surface = rgba(e0e2e8ff)

$on_background = rgba(e0e2e8ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(003355ff)

$on_primary_container = rgba(cfe5ffff)

$on_primary_fixed = rgba(001d34ff)

$on_primary_fixed_variant = rgba(124a73ff)

$on_secondary = rgba(243240ff)

$on_secondary_container = rgba(d5e4f7ff)

$on_secondary_fixed = rgba(0f1d2aff)

$on_secondary_fixed_variant = rgba(3a4857ff)

$on_surface = rgba(e0e2e8ff)

$on_surface_variant = rgba(c2c7cfff)

$on_tertiary = rgba(392a49ff)

$on_tertiary_container = rgba(f0dbffff)

$on_tertiary_fixed = rgba(231532ff)

$on_tertiary_fixed_variant = rgba(504060ff)

$outline = rgba(8c9199ff)

$outline_variant = rgba(42474eff)

$primary = rgba(9dcbfbff)

$primary_container = rgba(124a73ff)

$primary_fixed = rgba(cfe5ffff)

$primary_fixed_dim = rgba(9dcbfbff)

$scrim = rgba(000000ff)

$secondary = rgba(bac8daff)

$secondary_container = rgba(3a4857ff)

$secondary_fixed = rgba(d5e4f7ff)

$secondary_fixed_dim = rgba(bac8daff)

$shadow = rgba(000000ff)

$source_color = rgba(0e81cbff)

$surface = rgba(101418ff)

$surface_bright = rgba(36393eff)

$surface_container = rgba(1d2024ff)

$surface_container_high = rgba(272a2fff)

$surface_container_highest = rgba(32353aff)

$surface_container_low = rgba(181c20ff)

$surface_container_lowest = rgba(0b0e12ff)

$surface_dim = rgba(101418ff)

$surface_tint = rgba(9dcbfbff)

$surface_variant = rgba(42474eff)

$tertiary = rgba(d4bee6ff)

$tertiary_container = rgba(504060ff)

$tertiary_fixed = rgba(f0dbffff)

$tertiary_fixed_dim = rgba(d4bee6ff)


